<a href="https://colab.research.google.com/github/Appaji-Yadla/Appaji-Yadla/blob/main/NLP_Text_Data_Sentiment_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import numpy as np
import pandas as pd
import os

In [ ]:
os.chdir("/content/drive/MyDrive/Data Science_Innomatics/Data_Sets")
os.getcwd()

'/content/drive/MyDrive/Data Science_Innomatics/Data_Sets'

In [ ]:
os.listdir()

['carat_.jpg',
 'clarity_.jpg',
 'Iris.csv',
 'color.jpg',
 'diamonds.csv',
 'Data',
 'E:\\Nani\\Data Science\\Innomatics\\Assignments\\NLP\\NLP.csv',
 'NLP.csv']

In [ ]:
!ls

sample_data


In [ ]:
# Unzipping the data
!unzip "Data/text_data.zip" -d "Data/"

Streaming output truncated to the last 5000 lines.
  inflating: Data/text/file_198.txt  
  inflating: Data/text/file_1980.txt  
  inflating: Data/text/file_1981.txt  
  inflating: Data/text/file_1982.txt  
  inflating: Data/text/file_1983.txt  
  inflating: Data/text/file_1984.txt  
  inflating: Data/text/file_1985.txt  
  inflating: Data/text/file_1986.txt  
 extracting: Data/text/file_1987.txt  
  inflating: Data/text/file_1988.txt  
  inflating: Data/text/file_1989.txt  
 extracting: Data/text/file_199.txt  
  inflating: Data/text/file_1990.txt  
 extracting: Data/text/file_1991.txt  
  inflating: Data/text/file_1992.txt  
  inflating: Data/text/file_1993.txt  
  inflating: Data/text/file_1994.txt  
  inflating: Data/text/file_1995.txt  
  inflating: Data/text/file_1996.txt  
  inflating: Data/text/file_1997.txt  
  inflating: Data/text/file_1998.txt  
  inflating: Data/text/file_1999.txt  
  inflating: Data/text/file_2.txt    
  inflating: Data/text/file_20.txt   
  inflating: Data

In [ ]:
df = pd.DataFrame(columns=["text"])
files = os.listdir("Data/text")
for i in files:
  file_open = open("Data/text/"+i)
  data = file_open.read()
  df = df.append(pd.DataFrame([[data]], columns = ["text"]), ignore_index=True)
df

Streaming output truncated to the last 5000 lines.
<ipython-input-7-06e354d84531>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame([[data]], columns = ["text"]), ignore_index=True)
<ipython-input-7-06e354d84531>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame([[data]], columns = ["text"]), ignore_index=True)
<ipython-input-7-06e354d84531>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame([[data]], columns = ["text"]), ignore_index=True)
<ipython-input-7-06e354d84531>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame([[data]], c

text
0     Premise\nStudents can also have more chance of...
1                     Premise\nIndians don't eat beef\n
2     Premise\nthe company will earn more money and ...
3     Premise\nI made a month-long backpack trip thr...
4     Premise\nattending both girls and boys in a sa...
...                                                 ...
6084  Premise\nNorth American economists have publis...
6085  Claim\nthe methods to reduce the number of aut...
6086  Premise\nwomen find it difficult to balance th...
6087  Premise\nadvertisements have undeniable affect...
6088  Premise\nspaceships, communication satellites ...

[6089 rows x 1 columns]

In [ ]:
df.head()

text
0  Premise\nStudents can also have more chance of...
1                  Premise\nIndians don't eat beef\n
2  Premise\nthe company will earn more money and ...
3  Premise\nI made a month-long backpack trip thr...
4  Premise\nattending both girls and boys in a sa...

In [ ]:
df.tail()

text
6084  Premise\nNorth American economists have publis...
6085  Claim\nthe methods to reduce the number of aut...
6086  Premise\nwomen find it difficult to balance th...
6087  Premise\nadvertisements have undeniable affect...
6088  Premise\nspaceships, communication satellites ...

In [ ]:
df[['label', 'Text']] = df['text'].str.split('\n', 1, expand=True)

# Display the resulting DataFrame
print(df[['label', 'Text']])

        label                                               Text
0     Premise  Students can also have more chance of interact...
1     Premise                           Indians don't eat beef\n
2     Premise  the company will earn more money and reputatio...
3     Premise  I made a month-long backpack trip through Sout...
4     Premise  attending both girls and boys in a same school...
...       ...                                                ...
6084  Premise  North American economists have published repor...
6085    Claim  the methods to reduce the number of automobile...
6086  Premise  women find it difficult to balance their work ...
6087  Premise  advertisements have undeniable affects on the ...
6088  Premise  spaceships, communication satellites and space...

[6089 rows x 2 columns]


<ipython-input-10-e5a52b641e15>:1: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  df[['label', 'Text']] = df['text'].str.split('\n', 1, expand=True)


In [ ]:
df.head()

text    label  \
0  Premise\nStudents can also have more chance of...  Premise   
1                  Premise\nIndians don't eat beef\n  Premise   
2  Premise\nthe company will earn more money and ...  Premise   
3  Premise\nI made a month-long backpack trip thr...  Premise   
4  Premise\nattending both girls and boys in a sa...  Premise   

                                                Text  
0  Students can also have more chance of interact...  
1                           Indians don't eat beef\n  
2  the company will earn more money and reputatio...  
3  I made a month-long backpack trip through Sout...  
4  attending both girls and boys in a same school...

In [ ]:
df=df.drop('text', axis = 1)
df.head()

label                                               Text
0  Premise  Students can also have more chance of interact...
1  Premise                           Indians don't eat beef\n
2  Premise  the company will earn more money and reputatio...
3  Premise  I made a month-long backpack trip through Sout...
4  Premise  attending both girls and boys in a same school...

In [ ]:
df.tail()

label                                               Text
6084  Premise  North American economists have published repor...
6085    Claim  the methods to reduce the number of automobile...
6086  Premise  women find it difficult to balance their work ...
6087  Premise  advertisements have undeniable affects on the ...
6088  Premise  spaceships, communication satellites and space...

In [ ]:
df.to_csv("/content/drive/MyDrive/Data Science_Innomatics/Data_Sets/NLP.csv")

In [ ]:
df['label'].unique()

array(['Premise', 'Claim', 'MajorClaim'], dtype=object)

How many files are having 'Claim' label?

In [ ]:
(df['label']=='Claim').sum()

1506

How many files are having 'Premise' label?

In [ ]:
(df['label']=='Premise').sum()

3832

How many files are having 'MajorClaim' label?

In [ ]:
(df['label']=='MajorClaim').sum()

751

How many total files are given in the .txt format?

In [ ]:
df.describe()


label                                               Text
count      6089                                               6089
unique        3                                               6050
top     Premise  a government's role should be providing means ...
freq       3832                                                  3

In [ ]:
df.isnull().sum()

label    0
Text     0
dtype: int64

In [ ]:
# install nltk
!pip install nltk

In [ ]:
import nltk
nltk.download('stopwords')
# Downloading wordnet before applying Lemmatizer
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...


True

In [ ]:
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [ ]:
## initialise the inbuilt Stemmer
stemmer = PorterStemmer()
## We can also use Lemmatizer instead of Stemmer
lemmatizer = WordNetLemmatizer()

Text Preprocessing Steps

In [ ]:
def pre_processor(raw_text, flag):
   # Removing special characters and digits
  clean_text = re.sub("[^a-zA-Z]"," ",raw_text)

  # change sentence to lower case
  clean_text = clean_text.lower()

  # tokenize into words
  tokens = clean_text.split()

  # remove stop words
  clean_tokens = [i for i in tokens if i not in stopwords.words('english')]

   # Stemming/Lemmatization
  if (flag == 'stem'):
    clean_tokens = [stemmer.stem(word) for word in clean_tokens]
  else:
    clean_tokens = [lemmatizer.lemmatize(word) for word in clean_tokens]
  return pd.Series([" ".join(clean_tokens), len(clean_tokens)])

In [ ]:
# Stemming
New_df = df['Text'].apply(lambda x : pre_processor(x, 'stem'))

New_df.head()

0   1
0       student also chanc interact teacher classmat   6
1                                    indian eat beef   3
2     compani earn money reput worker excel knowledg   7
3  made month long backpack trip southeast asia l...  10
4       attend girl boy school caus mani disadvantag   7

What is the output if you apply all the text pre-processing on file_1?

In [ ]:
Stem_df = df['Text'].apply(lambda x : pre_processor(x, 'stem'))
Lem_df = df['Text'].apply(lambda x : pre_processor(x, 'lem'))


In [ ]:

Stem_df.columns = ['clean_text_stem', 'text_length_stem']
Lem_df.columns = ['clean_text_lemma', 'text_length_lemma']

In [ ]:
Stem_df.head(1)


clean_text_stem  text_length_stem
0  student also chanc interact teacher classmat                 6

In [ ]:
Lem_df.head(1)

clean_text_lemma  text_length_lemma
0  student also chance interaction teacher classmate                  6

After applying text cleaning (i.e. text pre-processing), what is the maximum number of word level tokens in the clean 'text' column?

In [ ]:
Stem_df['text_length_stem'].max()

31

In [ ]:
Lem_df['text_length_lemma'].max()

31

In [ ]:
Stem_df.describe()

text_length_stem
count       6089.000000
mean           8.434390
std            3.945174
min            1.000000
25%            6.000000
50%            8.000000
75%           10.000000
max           31.000000

In [ ]:
df = pd.concat([df, Stem_df], axis = 1)
df.head()

label                                               Text  \
0  Premise  Students can also have more chance of interact...   
1  Premise                           Indians don't eat beef\n   
2  Premise  the company will earn more money and reputatio...   
3  Premise  I made a month-long backpack trip through Sout...   
4  Premise  attending both girls and boys in a same school...   

                                     clean_text_stem  text_length_stem  
0       student also chanc interact teacher classmat                 6  
1                                    indian eat beef                 3  
2     compani earn money reput worker excel knowledg                 7  
3  made month long backpack trip southeast asia l...                10  
4       attend girl boy school caus mani disadvantag                 7

In [ ]:
df = pd.concat([df, Lem_df], axis = 1)
df.head()

label                                               Text  \
0  Premise  Students can also have more chance of interact...   
1  Premise                           Indians don't eat beef\n   
2  Premise  the company will earn more money and reputatio...   
3  Premise  I made a month-long backpack trip through Sout...   
4  Premise  attending both girls and boys in a same school...   

                                     clean_text_stem  text_length_stem  \
0       student also chanc interact teacher classmat                 6   
1                                    indian eat beef                 3   
2     compani earn money reput worker excel knowledg                 7   
3  made month long backpack trip southeast asia l...                10   
4       attend girl boy school caus mani disadvantag                 7   

                                    clean_text_lemma  text_length_lemma  
0  student also chance interaction teacher classmate                  6  
1                                    indian eat beef                  3  
2  company earn money reputation worker excellent...                  7  
3  made month long backpack trip southeast asia l...                 10  
4  attending girl boy school cause many disadvantage                  7

In [ ]:
# Bag of Words

from sklearn.feature_extraction.text import CountVectorizer

vocab = CountVectorizer()

DTM = vocab.fit_transform(df['clean_text_lemma'])


In [ ]:
#unique words
vocab.vocabulary_

{'student': 5131,
 'also': 222,
 'chance': 784,
 'interaction': 2896,
 'teacher': 5297,
 'classmate': 862,
 'indian': 2767,
 'eat': 1676,
 'beef': 492,
 'company': 963,
 'earn': 1663,
 'money': 3476,
 'reputation': 4518,
 'worker': 5923,
 'excellent': 1947,
 'knowledge': 3063,
 'made': 3264,
 'month': 3486,
 'long': 3225,
 'backpack': 450,
 'trip': 5528,
 'southeast': 4977,
 'asia': 346,
 'last': 3094,
 'summer': 5186,
 'girlfriend': 2373,
 'attending': 402,
 'girl': 2372,
 'boy': 598,
 'school': 4703,
 'cause': 748,
 'many': 3299,
 'disadvantage': 1493,
 'vital': 5790,
 'follow': 2220,
 'one': 3710,
 'religious': 4473,
 'practice': 4074,
 'bring': 624,
 'enlightenment': 1825,
 'mind': 3415,
 'forming': 2252,
 'language': 3087,
 'must': 3544,
 'undergone': 5601,
 'thousand': 5393,
 'year': 5958,
 'taxation': 5293,
 'may': 3337,
 'tackled': 5267,
 'environmental': 1860,
 'issue': 2979,
 'simply': 4863,
 'diverting': 1585,
 'people': 3901,
 'public': 4257,
 'transportation': 5498,
 'trai

In [ ]:
sorted(vocab.vocabulary_)

['aaa',
 'abandon',
 'abbreviated',
 'abbreviation',
 'abetter',
 'abiding',
 'ability',
 'able',
 'abovementioned',
 'abroad',
 'absence',
 'absent',
 'absolutely',
 'absolved',
 'absorb',
 'absorbed',
 'absorbing',
 'abstract',
 'absurd',
 'abundance',
 'abundant',
 'abuse',
 'abusive',
 'academic',
 'academically',
 'academy',
 'accelarates',
 'accelerate',
 'accept',
 'accepted',
 'access',
 'accessed',
 'accessibility',
 'accessible',
 'accessing',
 'accident',
 'accidentally',
 'acclaim',
 'accommodating',
 'accommodation',
 'accompanied',
 'accompany',
 'accompanying',
 'accomplish',
 'accomplished',
 'accomplishing',
 'accomplishment',
 'accordance',
 'according',
 'accordingly',
 'account',
 'accountable',
 'accounting',
 'accredited',
 'accumulate',
 'accumulated',
 'accumulating',
 'accumulation',
 'accuracy',
 'accurate',
 'accusation',
 'accuse',
 'accused',
 'accustomed',
 'achieve',
 'achieved',
 'achievement',
 'achieves',
 'achieving',
 'aching',
 'acid',
 'acing',
 'a

In [ ]:
print(DTM)

  (0, 5131)	1
  (0, 222)	1
  (0, 784)	1
  (0, 2896)	1
  (0, 5297)	1
  (0, 862)	1
  (1, 2767)	1
  (1, 1676)	1
  (1, 492)	1
  (2, 963)	1
  (2, 1663)	1
  (2, 3476)	1
  (2, 4518)	1
  (2, 5923)	1
  (2, 1947)	1
  (2, 3063)	1
  (3, 3264)	1
  (3, 3486)	1
  (3, 3225)	1
  (3, 450)	1
  (3, 5528)	1
  (3, 4977)	1
  (3, 346)	1
  (3, 3094)	1
  (3, 5186)	1
  :	:
  (6085, 3814)	1
  (6085, 3987)	1
  (6086, 2168)	1
  (6086, 5913)	1
  (6086, 5919)	1
  (6086, 5470)	1
  (6086, 5884)	1
  (6086, 1471)	1
  (6086, 4625)	1
  (6086, 455)	1
  (6087, 146)	1
  (6087, 4936)	1
  (6087, 157)	1
  (6087, 4171)	1
  (6087, 145)	1
  (6087, 5595)	1
  (6088, 222)	1
  (6088, 957)	1
  (6088, 4936)	1
  (6088, 3240)	1
  (6088, 1131)	1
  (6088, 3896)	1
  (6088, 4681)	1
  (6088, 4983)	1
  (6088, 4984)	1


In [ ]:
print(DTM.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
df_1 = pd.DataFrame(DTM.toarray(), columns=sorted(vocab.vocabulary_))
df_1

aaa  abandon  abbreviated  abbreviation  abetter  abiding  ability  \
0       0        0            0             0        0        0        0   
1       0        0            0             0        0        0        0   
2       0        0            0             0        0        0        0   
3       0        0            0             0        0        0        0   
4       0        0            0             0        0        0        0   
...   ...      ...          ...           ...      ...      ...      ...   
6084    0        0            0             0        0        0        0   
6085    0        0            0             0        0        0        0   
6086    0        0            0             0        0        0        0   
6087    0        0            0             0        0        0        0   
6088    0        0            0             0        0        0        0   

      able  abovementioned  abroad  ...  york  young  younger  youngster  \
0        0               0       0  ...     0      0        0          0   
1        0               0       0  ...     0      0        0          0   
2        0               0       0  ...     0      0        0          0   
3        0               0       0  ...     0      0        0          0   
4        0               0       0  ...     0      0        0          0   
...    ...             ...     ...  ...   ...    ...      ...        ...   
6084     0               0       0  ...     0      0        0          0   
6085     0               0       0  ...     0      0        0          0   
6086     0               0       0  ...     0      0        0          0   
6087     0               0       0  ...     0      0        0          0   
6088     0               0       0  ...     0      0        0          0   

      youth  zappa  zero  zone  zoo  zookeepers  
0         0      0     0     0    0           0  
1         0      0     0     0    0           0  
2         0      0     0     0    0           0  
3         0      0     0     0    0           0  
4         0      0     0     0    0           0  
...     ...    ...   ...   ...  ...         ...  
6084      0      0     0     0    0           0  
6085      0      0     0     0    0           0  
6086      0      0     0     0    0           0  
6087      0      0     0     0    0           0  
6088      0      0     0     0    0           0  

[6089 rows x 5974 columns]

In [ ]:
df_1.shape

(6089, 5974)

N-Gram Approach

In [ ]:
# Pure 2 grams
vocab = CountVectorizer(ngram_range=(2,2))

DTM = vocab.fit_transform(df['clean_text_lemma'])

In [ ]:
sorted(vocab.vocabulary_)

['aaa excellent',
 'abandon culture',
 'abandon job',
 'abandon lifelong',
 'abbreviated word',
 'abbreviation broken',
 'abetter environment',
 'abiding people',
 'ability able',
 'ability adapt',
 'ability adapting',
 'ability afford',
 'ability afternoon',
 'ability also',
 'ability among',
 'ability analyzing',
 'ability based',
 'ability class',
 'ability communicate',
 'ability consumption',
 'ability contribute',
 'ability deal',
 'ability define',
 'ability differentiate',
 'ability enough',
 'ability essential',
 'ability future',
 'ability help',
 'ability helpful',
 'ability learning',
 'ability needed',
 'ability people',
 'ability plan',
 'ability problem',
 'ability read',
 'ability regard',
 'ability relate',
 'ability relating',
 'ability several',
 'ability skill',
 'ability specific',
 'ability sport',
 'ability student',
 'ability survive',
 'ability work',
 'able afford',
 'able apply',
 'able ask',
 'able bring',
 'able browse',
 'able catch',
 'able cause',
 'able

In [ ]:
print(DTM.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
df_2 = pd.DataFrame(DTM.toarray(), columns=sorted(vocab.vocabulary_))
df_2

aaa excellent  abandon culture  abandon job  abandon lifelong  \
0                 0                0            0                 0   
1                 0                0            0                 0   
2                 0                0            0                 0   
3                 0                0            0                 0   
4                 0                0            0                 0   
...             ...              ...          ...               ...   
6084              0                0            0                 0   
6085              0                0            0                 0   
6086              0                0            0                 0   
6087              0                0            0                 0   
6088              0                0            0                 0   

      abbreviated word  abbreviation broken  abetter environment  \
0                    0                    0                    0   
1                    0                    0                    0   
2                    0                    0                    0   
3                    0                    0                    0   
4                    0                    0                    0   
...                ...                  ...                  ...   
6084                 0                    0                    0   
6085                 0                    0                    0   
6086                 0                    0                    0   
6087                 0                    0                    0   
6088                 0                    0                    0   

      abiding people  ability able  ability adapt  ...  zoo see  zoo serve  \
0                  0             0              0  ...        0          0   
1                  0             0              0  ...        0          0   
2                  0             0              0  ...        0          0   
3                  0             0              0  ...        0          0   
4                  0             0              0  ...        0          0   
...              ...           ...            ...  ...      ...        ...   
6084               0             0              0  ...        0          0   
6085               0             0              0  ...        0          0   
6086               0             0              0  ...        0          0   
6087               0             0              0  ...        0          0   
6088               0             0              0  ...        0          0   

      zoo spending  zoo still  zoo take  zoo towards  zoo useful  zoo would  \
0                0          0         0            0           0          0   
1                0          0         0            0           0          0   
2                0          0         0            0           0          0   
3                0          0         0            0           0          0   
4                0          0         0            0           0          0   
...            ...        ...       ...          ...         ...        ...   
6084             0          0         0            0           0          0   
6085             0          0         0            0           0          0   
6086             0          0         0            0           0          0   
6087             0          0         0            0           0          0   
6088             0          0         0            0           0          0   

      zookeepers also  zookeepers need  
0                   0                0  
1                   0                0  
2                   0                0  
3                   0                0  
4                   0                0  
...               ...              ...  
6084                0                0  
6085                0                0  
6086                0                0  
6087                0                0  

In [ ]:
df_2.shape

(6089, 35995)

In [ ]:
#3-gram
vocab = CountVectorizer(ngram_range=(3,3))
DTM = vocab.fit_transform(df['clean_text_lemma'])

In [ ]:
sorted(vocab.vocabulary_)

['aaa excellent teacher',
 'abandon job family',
 'abandon lifelong hobby',
 'abbreviated word shorten',
 'abbreviation broken language',
 'abetter environment also',
 'abiding people anywhere',
 'ability able cause',
 'ability adapt kind',
 'ability adapt oneself',
 'ability adapting oneself',
 'ability afford expensive',
 'ability afternoon class',
 'ability also essential',
 'ability among child',
 'ability analyzing matter',
 'ability based academic',
 'ability communicate understanding',
 'ability contribute development',
 'ability deal problem',
 'ability define necessary',
 'ability differentiate right',
 'ability enough tell',
 'ability essential well',
 'ability future become',
 'ability help lot',
 'ability helpful communicating',
 'ability learning childhood',
 'ability needed music',
 'ability plan organize',
 'ability problem solving',
 'ability read understand',
 'ability regard cooperation',
 'ability relate people',
 'ability relate well',
 'ability relating people',
 '

In [ ]:
print(DTM.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
df_3 = pd.DataFrame(DTM.toarray(), columns = sorted(vocab.vocabulary_))
df_3

aaa excellent teacher  abandon job family  abandon lifelong hobby  \
0                         0                   0                       0   
1                         0                   0                       0   
2                         0                   0                       0   
3                         0                   0                       0   
4                         0                   0                       0   
...                     ...                 ...                     ...   
6084                      0                   0                       0   
6085                      0                   0                       0   
6086                      0                   0                       0   
6087                      0                   0                       0   
6088                      0                   0                       0   

      abbreviated word shorten  abbreviation broken language  \
0                            0                             0   
1                            0                             0   
2                            0                             0   
3                            0                             0   
4                            0                             0   
...                        ...                           ...   
6084                         0                             0   
6085                         0                             0   
6086                         0                             0   
6087                         0                             0   
6088                         0                             0   

      abetter environment also  abiding people anywhere  ability able cause  \
0                            0                        0                   0   
1                            0                        0                   0   
2                            0                        0                   0   
3                            0                        0                   0   
4                            0                        0                   0   
...                        ...                      ...                 ...   
6084                         0                        0                   0   
6085                         0                        0                   0   
6086                         0                        0                   0   
6087                         0                        0                   0   
6088                         0                        0                   0   

      ability adapt kind  ability adapt oneself  ...  zoo serve relates  \
0                      0                      0  ...                  0   
1                      0                      0  ...                  0   
2                      0                      0  ...                  0   
3                      0                      0  ...                  0   
4                      0                      0  ...                  0   
...                  ...                    ...  ...                ...   
6084                   0                      0  ...                  0   
6085                   0                      0  ...                  0   
6086                   0                      0  ...                  0   
6087                   0                      0  ...                  0   
6088                   0                      0  ...                  0   

      zoo spending time  zoo still could  zoo take away  zoo towards human  \
0                     0                0              0                  0   
1                     0                0              0                  0   
2                     0                0              0                  0   
3                     0                0              0                  0   
4                     0                0              0                  0   
...               

In [ ]:
df_3.shape

(6089, 37757)

What is the total number of unique vocab words in the entire corpus?

In [ ]:
df_1.shape,df_2.shape,df_3.shape

((6089, 5974), (6089, 35995), (6089, 37757))

In [ ]:
#By using stemming
vocab = CountVectorizer(ngram_range=(1,1))

DTM = vocab.fit_transform(df['clean_text_stem'])
df_20 = pd.DataFrame(DTM.toarray(), columns=sorted(vocab.vocabulary_))


In [ ]:
vocab = CountVectorizer(ngram_range=(2,2))

DTM = vocab.fit_transform(df['clean_text_stem'])
df_21 = pd.DataFrame(DTM.toarray(), columns=sorted(vocab.vocabulary_))

In [ ]:
vocab = CountVectorizer(ngram_range=(3,3))

DTM = vocab.fit_transform(df['clean_text_stem'])
df_22 = pd.DataFrame(DTM.toarray(), columns=sorted(vocab.vocabulary_))

In [ ]:
df_20.shape,df_21.shape,df_22.shape

((6089, 4260), (6089, 34759), (6089, 37693))

What is the maximum number of character level tokens in a document present in the raw 'text' column?

In [ ]:
df

label                                               Text  \
0     MajorClaim  we should attach more importance to cooperatio...   
1        Premise  Take Olympic games which is a form of competit...   
2        Premise  The high technology and new ideas applied into...   
3        Premise  pollutions are not just caused by the burning ...   
4        Premise  the improvements of work efficiency also attri...   
...          ...                                                ...   
6084  MajorClaim  addressing pollution and traffic issues only b...   
6085     Premise  whether it can work out for alleviating traffi...   
6086     Premise  price control institution has been used in ple...   
6087       Claim  it seems not easy to increase petrol price ins...   
6088     Premise  governments have a macro-economic perspective ...   

                                        clean_text_stem  text_length_stem  \
0                     attach import cooper primari educ                 5   
1     take olymp game form competit instanc hard ima...                25   
2     high technolog new idea appli practic may lead...                15   
3     pollut caus burn oil chemic pollut extra light...                13   
4     improv work effici also attribut speed work pa...                13   
...                                                 ...               ...   
6084  address pollut traffic issu increas oil price ...                 8   
6085  whether work allevi traffic pollut pressur oug...                 8   
6086  price control institut use plenti social area ...                13   
6087           seem easi increas petrol price instantli                 6   
6088  govern macro econom perspect control price var...                11   

                                       clean_text_lemma  text_length_lemma  
0       attach importance cooperation primary education                  5  
1     take olympic game form competition instance ha...                 25  
2     high technology new idea applied practice may ...                 15  
3     pollution caused burning oil chemical pollutan...                 13  
4     improvement work efficiency also attribute spe...                 13  
...                                                 ...                ...  
6084  addressing pollution traffic issue increasing ...                  8  
6085  whether work alleviating traffic pollution pre...                  8  
6086  price control institution used plenty social a...                 13  
6087         seems easy increase petrol price instantly                  6  
6088  government macro economic perspective control ...                 11  

[6089 rows x 6 columns]

In [ ]:
df['len_Text'] = df['Text'].apply(lambda x : len(x))

In [ ]:
df

label                                               Text  \
0     MajorClaim  we should attach more importance to cooperatio...   
1        Premise  Take Olympic games which is a form of competit...   
2        Premise  The high technology and new ideas applied into...   
3        Premise  pollutions are not just caused by the burning ...   
4        Premise  the improvements of work efficiency also attri...   
...          ...                                                ...   
6084  MajorClaim  addressing pollution and traffic issues only b...   
6085     Premise  whether it can work out for alleviating traffi...   
6086     Premise  price control institution has been used in ple...   
6087       Claim  it seems not easy to increase petrol price ins...   
6088     Premise  governments have a macro-economic perspective ...   

                                        clean_text_stem  text_length_stem  \
0                     attach import cooper primari educ                 5   
1     take olymp game form competit instanc hard ima...                25   
2     high technolog new idea appli practic may lead...                15   
3     pollut caus burn oil chemic pollut extra light...                13   
4     improv work effici also attribut speed work pa...                13   
...                                                 ...               ...   
6084  address pollut traffic issu increas oil price ...                 8   
6085  whether work allevi traffic pollut pressur oug...                 8   
6086  price control institut use plenti social area ...                13   
6087           seem easi increas petrol price instantli                 6   
6088  govern macro econom perspect control price var...                11   

                                       clean_text_lemma  text_length_lemma  \
0       attach importance cooperation primary education                  5   
1     take olympic game form competition instance ha...                 25   
2     high technology new idea applied practice may ...                 15   
3     pollution caused burning oil chemical pollutan...                 13   
4     improvement work efficiency also attribute spe...                 13   
...                                                 ...                ...   
6084  addressing pollution traffic issue increasing ...                  8   
6085  whether work alleviating traffic pollution pre...                  8   
6086  price control institution used plenty social a...                 13   
6087         seems easy increase petrol price instantly                  6   
6088  government macro economic perspective control ...                 11   

      len_Text  
0           73  
1          298  
2          155  
3          138  
4          128  
...        ...  
6084        85  
6085        93  
6086       132  
6087        53  
6088       108  

[6089 rows x 7 columns]

In [ ]:
df['len_Text'].max()

345

In [ ]:
df['len_Text'].describe()

count    6089.000000
mean       93.468878
std        42.660546
min        17.000000
25%        62.000000
50%        86.000000
75%       116.000000
max       345.000000
Name: len_Text, dtype: float64

What is the maximum number of word level tokens in raw 'text' columns?

In [ ]:
df['Split_Text'] = df['Text'].apply(lambda x : x.split())
df

label                                               Text  \
0     MajorClaim  we should attach more importance to cooperatio...   
1        Premise  Take Olympic games which is a form of competit...   
2        Premise  The high technology and new ideas applied into...   
3        Premise  pollutions are not just caused by the burning ...   
4        Premise  the improvements of work efficiency also attri...   
...          ...                                                ...   
6084  MajorClaim  addressing pollution and traffic issues only b...   
6085     Premise  whether it can work out for alleviating traffi...   
6086     Premise  price control institution has been used in ple...   
6087       Claim  it seems not easy to increase petrol price ins...   
6088     Premise  governments have a macro-economic perspective ...   

                                        clean_text_stem  text_length_stem  \
0                     attach import cooper primari educ                 5   
1     take olymp game form competit instanc hard ima...                25   
2     high technolog new idea appli practic may lead...                15   
3     pollut caus burn oil chemic pollut extra light...                13   
4     improv work effici also attribut speed work pa...                13   
...                                                 ...               ...   
6084  address pollut traffic issu increas oil price ...                 8   
6085  whether work allevi traffic pollut pressur oug...                 8   
6086  price control institut use plenti social area ...                13   
6087           seem easi increas petrol price instantli                 6   
6088  govern macro econom perspect control price var...                11   

                                       clean_text_lemma  text_length_lemma  \
0       attach importance cooperation primary education                  5   
1     take olympic game form competition instance ha...                 25   
2     high technology new idea applied practice may ...                 15   
3     pollution caused burning oil chemical pollutan...                 13   
4     improvement work efficiency also attribute spe...                 13   
...                                                 ...                ...   
6084  addressing pollution traffic issue increasing ...                  8   
6085  whether work alleviating traffic pollution pre...                  8   
6086  price control institution used plenty social a...                 13   
6087         seems easy increase petrol price instantly                  6   
6088  government macro economic perspective control ...                 11   

      len_Text                                         Split_Text  
0           73  [we, should, attach, more, importance, to, coo...  
1          298  [Take, Olympic, games, which, is, a, form, of,...  
2          155  [The, high, technology, and, new, ideas, appli...  
3          138  [pollutions, are, not, just, caused, by, the, ...  
4          128  [the, improvements, of, work, efficiency, also...  
...        ...                                                ...  
6084        85  [addressing, pollution, and, traffic, issues, ...  
6085        93  [whether, it, can, work, out, for, alleviating...  
6086       132  [price, control, institution, has, been, used,...  
6087        53  [it, seems, not, easy, to, increase, petrol, p...  
6088       108  [governments, have, a, macro-economic, perspec...  

[6089 rows x 8 columns]

In [ ]:
df['Split_Text_length'] = df['Split_Text'].apply(lambda x : len(x))
df

label                                               Text  \
0     MajorClaim  we should attach more importance to cooperatio...   
1        Premise  Take Olympic games which is a form of competit...   
2        Premise  The high technology and new ideas applied into...   
3        Premise  pollutions are not just caused by the burning ...   
4        Premise  the improvements of work efficiency also attri...   
...          ...                                                ...   
6084  MajorClaim  addressing pollution and traffic issues only b...   
6085     Premise  whether it can work out for alleviating traffi...   
6086     Premise  price control institution has been used in ple...   
6087       Claim  it seems not easy to increase petrol price ins...   
6088     Premise  governments have a macro-economic perspective ...   

                                        clean_text_stem  text_length_stem  \
0                     attach import cooper primari educ                 5   
1     take olymp game form competit instanc hard ima...                25   
2     high technolog new idea appli practic may lead...                15   
3     pollut caus burn oil chemic pollut extra light...                13   
4     improv work effici also attribut speed work pa...                13   
...                                                 ...               ...   
6084  address pollut traffic issu increas oil price ...                 8   
6085  whether work allevi traffic pollut pressur oug...                 8   
6086  price control institut use plenti social area ...                13   
6087           seem easi increas petrol price instantli                 6   
6088  govern macro econom perspect control price var...                11   

                                       clean_text_lemma  text_length_lemma  \
0       attach importance cooperation primary education                  5   
1     take olympic game form competition instance ha...                 25   
2     high technology new idea applied practice may ...                 15   
3     pollution caused burning oil chemical pollutan...                 13   
4     improvement work efficiency also attribute spe...                 13   
...                                                 ...                ...   
6084  addressing pollution traffic issue increasing ...                  8   
6085  whether work alleviating traffic pollution pre...                  8   
6086  price control institution used plenty social a...                 13   
6087         seems easy increase petrol price instantly                  6   
6088  government macro economic perspective control ...                 11   

      len_Text                                         Split_Text  \
0           73  [we, should, attach, more, importance, to, coo...   
1          298  [Take, Olympic, games, which, is, a, form, of,...   
2          155  [The, high, technology, and, new, ideas, appli...   
3          138  [pollutions, are, not, just, caused, by, the, ...   
4          128  [the, improvements, of, work, efficiency, also...   
...        ...                                                ...   
6084        85  [addressing, pollution, and, traffic, issues, ...   
6085        93  [whether, it, can, work, out, for, alleviating...   
6086       132  [price, control, institution, has, been, used,...   
6087        53  [it, seems, not, easy, to, increase, petrol, p...   
6088       108  [governments, have, a, macro-economic, perspec...   

      Split_Text_length  
0                    10  
1                    58  
2                    26  
3                    20  
4                    19  
...                 ...  
6084                 13  
6085                 15  
6086                 23  
6087                  9  
6088                 15  

[6089 rows x 9 columns]

In [ ]:
df['Split_Text_length'].max()

67